services:
  db:
    image: postgres:15-alpine
    container_name: meu-postgres
    environment:
      POSTGRES_DB: sistema_financeiro         
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: 123
      TZ: America/Sao_Paulo
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./financeiro
    container_name: sistema-financeiro-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sistema_financeiro
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      TZ: America/Sao_Paulo

  frontend:
    build: ./front
    container_name: sistema-financeiro-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: